version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: templates/hair-salon/Dockerfile
    ports:
      - '3100:3100'
    environment:
      - NODE_ENV=development
    volumes:
      - ./templates/hair-salon:/app/templates/hair-salon
      - /app/node_modules
